### PR TITLE
added LSF job array and exit status handling subroutine to Forwarder.gro...

### PR DESCRIPTION
**Pull request by sb43**
changes were made in following three scripts:
Forwarder.groovy
FordwardHost.groovy
LsfCommandExecutor.groovy

### CODE REVIEW

**Comment by jsmedmar** [comment]
This is needed.

**Comment by sb43** [comment]
Current fork available at 
https://github.com/sb43/bpipe

**Comment by gdevenyi** [comment]
I believe the future for cluster-integration with bpipe is to transform all executors to the template-based as in https://github.com/ssadedin/bpipe/issues/163 and https://github.com/ssadedin/bpipe/issues/156 and https://github.com/ssadedin/bpipe/tree/sge_fixes

I'm currently using the sge_fixes branch for my local SGE and it works well.

**Comment by jsmedmar** [comment]
@sb43, I tried your fork (the lastest realease available), but I keep getting this error:

```
java.lang.ClassNotFoundException: bpipe.Runner
	at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:175)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:147)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:96)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:128)
```

**Comment by jsmedmar** [comment]
I think I'm having a problem related to this issue. I have a branch which executes a `bsub` job with an array of nodes, then it performs a check. The problem is that if one of the arrays is DONE, the bpipe thinks that the whole execution is completed.  Therefore, the check fails. @sb43's pull request addresses this issue, but I've not been able to test it due to the error I presented in my previous comment.

**Comment by jsmedmar** [comment]
@sb43's fork effectively fixes the issue. It enables bpipe to handle job arrays. I create this little example to recreate the problem: https://github.com/leukgen/bpipearrays. The pipe runs successfully with @sb43's fork but it fails with bpipe latest release (0.9.9_beta_1).

**Comment by ssadedin** [comment]
This would be good to try and integrate at the same time as moving the LSF support over to the template based system for job execution. The solution offered by @sb43, although extremely useful (and much appreciated!), isn't well aligned with how I hope the design to work in the future. So my plan would be to use that as a guide but to implement job array support independently.

Unfortunately I don't have access to an LSF system to test with at the moment. I have one rather simple question - would it be reasonable to test and develop the job array feature against an OpenLava installation? I am not sure how identical they are at this level.

**Comment by jsmedmar** [comment]
I think it does make sense. OpenLava argues to be IBM Platform LSF compatible. Once developed, we can test in our LSF environments and provide feedback. It would nice to have @sb43's thoughts on this.

**Comment by sb43** [comment]
Sorry @jsmedmar for not replying on your earlier comment regarding installation issue, good to know that it is resolved and the LSF fix is working at your end.
I agree with @ssadedin to implement the LSF support as per his existing framework, my implementation is just a workaround. I am happy to try and provide feedback on new developments in bpipe's LSF compatibility.
I have added a subroutine ( parseBjobs) to handle the LSF-jobarray's in  src/main/groovy/bpipe/Forwarder.groovy which basically writes 0 or 1 status in .exit file  based on LSF array job status after completion.  Hope this helps @ssadedin to implement the LSF support in his existing bpipe framework. 
Let me know if you need more information.

**Comment by ssadedin** [comment]
I have created the following issue to track work on this feature: https://github.com/ssadedin/bpipe/issues/168

Implementation is occurring in a new branch: 

https://github.com/ssadedin/bpipe/tree/lsf_array

Closing this request, please continue discussion in issue https://github.com/ssadedin/bpipe/issues/168.

Thanks everyone for the discussion & help on this problem!

**Pull request closed without merging**
